### ISSUE TITLE
Stream becomes slideshow after script is applied

### ISSUE THREAD

**Issue by ghost** [Cutwell/gif-avatar#1]
OBS videostream becomes slideshow (down to 3 fps from 30) after script was applied with any kind of image (gif, png, jpeg).
CPU load is normal.
OBS version 27.1.3 (64-bit).
Python 3.6.7-amd64.

**Comment by Cutwell** [comment]
Testing:
- Narrowed bug into update() function, apparently occurs when holding sources. 
- No impact on system memory, cpu or gpu load.
- Typical fixes (run as admin, etc.) do not work.

Fixes:
- Implemented different source toggling script, from verified working OBS script.
- Added script state memory, to prevent script from accessing scene when unnecessary.

Outcome: 
- Issue still occuring.

Some optimisations have theoretically been made through testing, but it seems the root issue is with OBS and how it is siezing / releasing sources. As we're now using identical code to a verified working script, the issue is most likely some unusual interaction we're yet to pin down.

**Comment by Cutwell** [comment]
Opened an active branch for this issue, if you can do any further testing then use the new main.py script from there.

**Comment by Cutwell** [comment]
Identified issue with audio monitoring, we were creating/destroying a SoundDevice stream object each interval, meaning memory consumption was stable however performance was impacted due to blocking to recreate stream per interval.

Fixed by moving stream to a permanent source, and reading from buffer each interval instead.
